# 指定项目端口号
server:
  port: 9000

spring:
  application:
    name: chuxuan-backend

  # autoconfigure:
  #   exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    mongodb:
      uri: mongodb+srv://guloujie:PJFyq91p2qbb1C8W@zpddyz.t91k4nn.mongodb.net/test    
      database: zack
  # jpa:
  #   # database: MYSQL
  #   # database-platform: org.hibernate.dialect.MySQL5Dialect
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.MySQLDialect
  #       # dialect: org.hibernate.dialect.MySQL5Dialect
  #   hibernate:
  #     generate-ddl: true # 需要加上这个才能自动生成数据库表
  #     ddl-auto: update

springfox:
  documentation:
    open-api:
      v3:
        path: /v3/api-docs    
management:
  endpoints:
    web:
      exposure:
        include: '*'